# Fix OpenJDK builds
# See: https://github.com/travis-ci/travis-ci/issues/5227
# sudo: false

sudo: required
dist: xenial
group: edge

language: java
jdk:
  - oraclejdk11
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk10
#  - openjdk11

os:
  - linux
  - osx
#  - windows

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura

addons:
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java8-installer
